name: Dork MacOS Build

on:
  push:
    paths:
      - ".github/workflows/macos.yaml"


jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup apple stuff
        run: |
          softwareupdate --install-rosetta --agree-to-license

      - name: install software
        run: |
          curl -sLo jai-beta.zip "https://www.dropbox.com/scl/fi/lll53073ht2ly7jyaoq42/jai-beta-2-029.zip?rlkey=zol2t8nq5gyn45cxs59dbypqk&dl=1"
          unzip jai-beta.zip
          chmod +x jai/bin/*
          echo "$PWD/jai/bin" >> $GITHUB_PATH

      - name: build with jai
        run: |
          arch -x86_64 zsh -c "
            cd stb_c_lexer
            clang -x c -DSTB_C_LEXER_IMPLEMENTATION -c stb_c_lexer.h -o stb_c_lexer.o
            ar rcs libstb_c_lexer.a stb_c_lexer.o
            clang -x c -DSTB_C_LEXER_IMPLEMENTATION -c stb_c_lexer.h -o stb_c_lexer.o
            clang -dynamiclib stb_c_lexer.o -o libstb_c_lexer.dylib
            mkdir libs/macos
            mv libstb_c_lexer.dylib libs/macos
            mv libstb_c_lexer.a libs/macos
            zip -r stb_mac.zip libs/macos/
            curl -X DELETE "https://upfast.cronyakatsuki.xyz/files/stb_mac.zip"
            curl -F 'file=@stb_mac.zip' 'https://upfast.cronyakatsuki.xyz'
            cd ..
            jai-macos example.jai
            curl -X DELETE "https://upfast.cronyakatsuki.xyz/files/example"
            curl -F 'file=@example' 'https://upfast.cronyakatsuki.xyz'
          "

