name: Dork MacOS Build

on:
  push:
    paths:
      - ".github/workflows/macos.yaml"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup apple stuff
        run: |
          softwareupdate --install-rosetta --agree-to-license

      - name: install software
        run: |
          curl -sLo jai-beta.zip "https://www.dropbox.com/scl/fi/lll53073ht2ly7jyaoq42/jai-beta-2-029.zip?rlkey=zol2t8nq5gyn45cxs59dbypqk&dl=1"
          unzip jai-beta.zip
          chmod +x jai/bin/*
          echo "$PWD/jai/bin" >> $GITHUB_PATH

      - name: build with jai
        run: |
          cd stb_c_lexer
          arch -x86_64 zsh -c "
            jai-macos generate.jai
            mkdir stb_mac
            mv libs stb_mac
            mv macos.jai stb_mac
            zip -r stb_mac.zip stb_mac/
            curl -F 'file=@stb_mac.zip' 'https://upfast.cronyakatsuki.xyz'
          "

